name: Generate YouTube Live M3U

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  generate-m3u:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        # Cài đặt thư viện siêu việt yt-dlp
        run: pip install yt-dlp

      - name: Run Python script to generate M3U
        run: python get_live.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add youtube_live.m3u
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update YouTube live streams" && git push)
